# Site settings
title: Sagamore
email: fayne@mobilenowgroup.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/sagamore" # the subpath of your site, e.g. /blog/
url: "http://fayne-mobilenow.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
env: "dev"

#Exclude
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'npm-debug.log']

# Build settings
markdown: kramdown

# Collections
collections:
  - team
  - features
  - work
  - slider
  - fund_investments
  - direct_investments
  - contact

#permalink
permalink:   /:categories/:title/

prose:
  rooturl: ''
  siteurl: 'http://fayne-mobilenow.github.io/sagamore/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'images'
  ignore:
    - /_layouts
    - /_sass
    - /_includes
    - /css
    - /js
    - /.gitignore
    - /about.md
    - feed.xml
    - package.json
    - Gruntfile.js
  metadata:
    _direct_investments:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "subtitle"
        field:
          element: "text"
          label: "Subtitle"
          placeholder: "This is a subtitle"
      - name: "image"
        field:
          element: "text"
          label: "Logo Image"
          placeholder: "Input the image URL"
      - name: "inversed_image"
        field:
          element: "text"
          label: "Inversed Logo Image"
          placeholder: "Input the inversed image URL"
      - name: "href"
        field:
          element: "text"
          label: "Link"
          placeholder: "Input the link"
      - name: "description"
        field:
          element: "text"
          label: "Full description"
          placeholder: "This is the description field"
      - name: "effect"
        field:
          element: "select"
          label: "Hover effect"
          options:
            - name: "Slide Up"
              value: "slide_up"
            - name: "Slide Down"
              value: "slide_down"
            - name: "Slide Left"
              value: "slide_left"
            - name: "Slide Right"
              value: "slide_right"
            - name: "Slide Corner"
              value: "slide_corner"
            - name: "Rotate"
              value: "rotate"
      - name: "sort"
        field:
          element: "text"
          label: "Sort"
          type: "text"
    _fund_investments:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "This is the description field"
      - name: "sort"
        field:
          element: "text"
          label: "Sort"
          type: "text"
    _slider:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "caption"
        field:
          element: "text"
          label: "Caption"
      - name: "image"
        field:
          element: "text"
          label: "Image"
      - name: "thumb"
        field:
          element: "text"
          label: "Thumb"
          placeholder: "Please input same picture path as Image field."
      - name: "transition"
        field:
          element: "select"
          label: "Transition"
          options:
            - name: "Fade"
              value: "fade"
      - name: "speed"
        field:
          element: "text"
          label: "Speed"
          value: "300"
      - name: "sort"
        field:
          element: "text"
          label: "Sort"
          type: "text"
    _team:
      - name: "name"
        field:
          element: "text"
          label: "Name"
      - name: "image"
        field:
          element: "text"
          label: "Image"
      - name: "position"
        field:
          element: "text"
          label: "Position"
      - name: "description"
        field:
          element: "text"
          label: "Description"
      - name: "sort"
        field:
          element: "text"
          label: "Sort"
    _contact:
      - name: "title"
        field:
          element: "text"
          lable: "Title"
      - name: "address"
        field:
          element: "text"
          lable: "Address"
      - name: "telphone"
        field:
          element: "text"
          lable: "Telphone"
      - name: "email"
        field:
          element: "text"
          lable: "Email"
      - name: "sort"
        field:
          element: "text"
          label: "Sort"